on: 
  workflow_dispatch:
    inputs:
          logLevel:
            description: 'Log level'
            required: false
            default: 'warning'
            type: choice
            options:
            - info
            - warning
            - debug

  push: 
    branches: [ main ]
    paths: 
    - 'factorial.py' 
    - 'lint.py' 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v4 

    - name: Set up Python 3.8 
      uses: actions/setup-python@v3
      with: 
        python-version: 3.8 

    - name: Install dependencies 
      run: | 
        python3 -m pip install --upgrade pip 
        pip3 install pylint 

    - name: Lint with pylint 
      run: | 
        python3 lint.py 
